CREATE TABLE [dbo].[Proxy](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProxyName] [varchar](150) NOT NULL,
	[Revision] [smallint] NOT NULL,
	[Description] [varchar](1000) NULL,
 CONSTRAINT [PK_Proxy] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO